// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwzvrktuezwausshinbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3enZya3R1ZXp3YXVzc2hpbmJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NjE3MTQsImV4cCI6MjA3MTUzNzcxNH0.fLKTUKTMaScQSIMwh1IWGvO5EERrVd7JCH-g_TD3CTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});