// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szisowtjjhcssdzrxnse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6aXNvd3Rqamhjc3NkenJ4bnNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjg5MTUsImV4cCI6MjA3MTkwNDkxNX0.D_Ya0bU-OgP32L51ISRW_lUzipQ5fpsYkwJewEOjGX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});